# 端口
server:
  port: 14001

mybatis:
  typeAliasesPackage: com.redis.lock.demo.entity
  mapper-locations: classpath:mybatis/com/redis/lock/demo/mapper/*.xml, classpath:mybatis/com/redis/lock/demo/mapper/custom/*.xml

# 抛出异常, 自定义错误消息体
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources.add-mappings: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo_shop?useLegacyDatetimeCode=false&serverTimezone=GMT+0
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 1
      minIdle: 3
      maxActive: 20
      maxWait: 5000
      timeBetweenEvictionRunsMillis: 30000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true; druid.stat.slowSqlMillis=2000
      useGlobalDataSourceStat: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:

logging:
  level:
    com.example.demo.dao : debug
